name: "DAST Scan"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  zap-scan:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: https://r3dg33k.com
          fail_action: false
          cmd_options: '-a'
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report_html.html

  dastardly-scan:
    name: Dastardly Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: https://r3dg33k.com
          output-filename: dastardly-report.xml
      - name: Upload Dastardly Report
        uses: actions/upload-artifact@v4
        with:
          name: dastardly-report
          path: dastardly-report.xml
