name: "DAST Scan"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy"]
    types:
      - completed

jobs:
  zap-scan:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: https://r3dg33k.com
          fail_action: false
          cmd_options: '-a'
          format: html
          report_file: zap-report.html
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

  dastardly-scan:
    name: Dastardly Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Dastardly
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: https://r3dg33k.com
          output-file: dastardly-report.html
      - name: Upload Dastardly Report
        uses: actions/upload-artifact@v4
        with:
          name: dastardly-report
          path: dastardly-report.html
